### PR TITLE
Update `GOVERNANCE.md` with link to Flux governance doc

### PR DESCRIPTION
**Pull request by todaywasawesome**
Remove confusion around Flux and change words to GitOps Working Group.

### CODE REVIEW

**Comment by todaywasawesome** [comment]
Signed-off-by: Dan Garfield dan@codefresh.io

**Comment by stefanprodan** [comment]
While this repo exists in the FluxCD org it must comply with Flux Governance. When the GitOps WG will have its own organisation then the maintainers  can create a new governance.

**Comment by csand-msft** [comment]
Signed-off-by: Chris Sanders csand@microsoft.com

**Comment by hiddeco** [comment]
I suggest that instead of changing the contents, we create a link to the `GOVERNANCE.md` document in the `fluxcd/community` repository. Something like:

> The GitOps Working Group follows the governance process described in <https://github.com/fluxcd/community/blob/main/GOVERNANCE.md>.

We also do this for the Code of Conduct and this works well: https://github.com/fluxcd/gitops-working-group/blob/main/CODE_OF_CONDUCT.md.

**Comment by squaremo** [comment]
I don't think there's any need for this. While the working group' workings are here, you operate under Flux's governance. A reference to that, as Hidde suggests, is not necessary but fine to have.

**Comment by todaywasawesome** [comment]
@hiddeco Good idea, I think that's a reasonable approach for now. 

@squaremo @stefanprodan I updated the PR to just reference the Governance document with @hiddeco's suggestion.

**Review by hiddeco — APPROVED** [review]

**Review by stefanprodan — APPROVED** [review]

**Pull request merged**
